In [2]:
import numpy as np

np.random.seed(0)   

In [ ]:
# آرایه یک بعدی با 4 عنصر رندوم
# 1d array with 4 random value

x = np.random.randint(10, size=4)      # 0 to 9
x = np.random.randint(0,10 , size=4)   # 0 to 9


print(x)


In [ ]:
# آرایه دو بعدی 2 در 4 با عناصر رندوم
# 2d 2 in 4 array with random values

x = np.random.randint(10, size= (2,4) )

print(x)


In [ ]:
# آرایه سه بعدی، سه تا 2 در 4 با عناصر رندوم
# 2d 3 * 2 in 4 array with random values

x = np.random.randint(10, size= (3,2,4) )

print(x)


In [ ]:
# فهمیدن مشخصات مربوط به یک آرایه
# find imformation about array

x = np.random.randint(10, size= (3,4,4) )


# بعد
# dimension
print(x.ndim)


# چند در چند بودن
#shape
print(x.shape)


# تعداد کل مقدادیر که حاصل ضرب ابعاد در هم است
# number of all values equal to multiply of dimensions
# 3 * 4 * 4 = 48
print(x.size)


# پیدا کردن دیتا تایپ
# find data type
print(x.dtype)



#جحم
#size
print(x.itemsize, "Bytes")
print(x.nbytes, "Bytes")

***Data types***

<pre>
    i - integer
    b - boolean
    u - unsigned integer
    f - float
    c - complex float
    m - timedelta
    M - datetime
    O - object
    S - string
    U - unicode string
    V - fixed chunk of memory for other type ( void )


'hello'  ->   U5
'hello world'  ->   U11  
array(['hello world', 'hello']).dtype   ->  U11

i4  ->  intiger 4 byte
U11 ->  unicode string 11 Byte

i8 -> int64  -> 8 Byte  -> max 16 number
i4 -> int32  -> 4 Byte  -> max 10 number
i2 -> int16  -> 2 Byte  -> max 5 number
i1 -> int8   -> 1 Byte  -> max 3 number 
                           for more number we must convert to O(object)


</pre>

In [14]:
# دیتا تایپ ها یا انواع داده
# data type

# dtype in array if not give : minimum type required to hold the objects in the sequence.
# را اگر به آرایه ندهیم، به صورت خودکار بهترین حالت رو انتخاب میکنه dtype

x = np.array([1.1, 2.1, 3.1])

print(x)

#see data type / دیدن نوع داده ای
print(x.dtype)

#change data type / تغییر نوع داده
x = x.astype('i')
x = x.astype(int)
print(x)
print(x.dtype)



#change int type to bool / تبدیل تایپ عددی به بولین
# ==0 -> False   =!0 -> True
x = np.array([1, 0, -4, 10], dtype=bool)
print(x)






## x = np.array(['a', '2', '3'], dtype='i')  # --> error  (can't convert string to int)



[1.1 2.1 3.1]
float64
[1 2 3]
int32
[ True False  True  True]


In [260]:
# دسترسی به جایگاه
# Access to the position

np.random.seed(0)

x = np.random.randint(10, size=(3,3,3))

#fist array from 3 array - secend row - secend column 
#اولین آرایه - سطر دوم - ستون دوم
print(x[0,1,1])  # [0,1,1] = [0][1][1]

#change vlaue 
# تغییر مقدار
x[0,1,1] = 8

# change all secend row value of first array
# تغییر کل مقادیر سطر دوم از آرایه اول
x[0,1,:] = 100


7
8
[[[  5   0   3]
  [100 100 100]
  [  3   5   2]]

 [[  4   7   6]
  [  8   8   1]
  [  6   7   7]]

 [[  8   1   5]
  [  9   8   9]
  [  4   3   0]]]


*نکته*
<br>
اگر تایپ آرایه ما، عدد صحیح باشه و ما یک مقدارش رو عدد اعشاری کنیم
آرایه نمیتواند، عدد اعشاری رو قبول کند، در نتیجه فقط قسمت صحیح گرفته میشود
<br>
<br>
*point*
<br>
If our array is type is like "int32", if we set a value to a float number, The array cannot accept a float number, so only the integer is taken

In [ ]:
# برش دادن
# slicing

np.random.seed(0)

x = np.random.randint(25, size=(8,4))

# select first row
print(x[0])  # [0, :]

# select first column
print(x[:,0])


# [:10]  -> index 0, 1,...,9  (10 -1)

# 2 ray and 2 column / دو سطر و سه ستون
print(x[:2, :3])

# سه سطر و سه ستون با فاصله یکی در میان
# 3row & 3column & decussate
print(x[:3, :3:2])

# برعکس کردن همه ی آرایه
# reverse all array
print(x[::-1, ::-1])




In [263]:
# تولید عدد و آرایه تکراری
# Generate a rapeat number and array

# repeat 3 for 4 times / سه رو 4 بار تکرار کن
print(np.repeat(3, 4))

x = np.array([[1,2],[3,4]])
print(np.repeat(x, 2, axis=None))


print(np.repeat(x, 3, axis=1))


print(np.repeat(x, [1, 2], axis=0))


[3 3 3 3]
[1 1 2 2 3 3 4 4]
[[1 1 1 2 2 2]
 [3 3 3 4 4 4]]
[[1 2]
 [3 4]
 [3 4]]


In [ ]:
# انتخاب شرطی
# Conditional selection

# np.random.seed(0)

x = np.random.randint(1,9, size= 10)
y = np.random.randint(0,2, size= 10)

print(x)
print(y)

# یشان برابر با 1 باشد y که x انتخاب مقدادیر  
# select all "x" values that "y" equal to 1 (y == 1)
print(x[y==1])


In [ ]:
# تغییر اندازه 
# reshape

x = np.random.randint(10, size=(4,5))

print('\n first : \n' , x)

# یک بعدی کردن
# Transfer to one dimensional
print(x.reshape(20,))
print(x.reshape(x.size,))

x = x.reshape(x.size,)

# دو بعدی کردی
# Transfer to two dimensional
print(x.reshape(2, 10))
print(x.reshape(20, 1))

# سه بعدی کردی
# Transfer to three dimensional
print(x.reshape(2, 2, 5))


In [ ]:
# ایجاد عدد رندم بین دو بازه
# generate a random number between two numbers


# بین 1 تا 10 صد عدد بساز
# genatate 100 number bitween 1 and 10
x = np.linspace(1,10, 100)
print(x)





In [6]:
# ایجاد یک توالی و رنج
# Create a sequence of numbers 

x = np.arange(6)   # 0 to 5
print(x)


x = np.arange(0, 10, 0.5)
print(x)




[0 1 2 3 4 5]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


In [ ]:
# ادغام دو آرایه
# concatenate


# concatenate
x = np.array([1,2,3])
y = np.array([4,5,6])

print(np.concatenate([x,y]))


# vstack
x = np.array(
    [[9, 8, 7],
    [6, 5, 4]]
    )

y = np.array([3, 2, 1])

#vstack
print(np.vstack([x,y]))


x = np.array((1, 2, 3))
y = np.array((4, 5, 6))

#hstack
print(np.hstack([x,y]))

a = np.array([[1],[2],[3]])
b = np.array([[4],[5],[6]])

#hstack
print(np.hstack([a,b]))


In [16]:
# برعکس کردن بعد یا بر عکس کردن سطر و ستون
# reverse rows and columns
import numpy as np

x1 = np.arange(1, 11)
x2 = np.arange(11, 21)

arr = np.array([x1, x2])
print(arr.shape)
print(arr)

arr_reverse = arr.T
print(arr_reverse.shape)
print(arr_reverse)


(2, 10)
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
(10, 2)
[[ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]
 [ 5 15]
 [ 6 16]
 [ 7 17]
 [ 8 18]
 [ 9 19]
 [10 20]]


In [ ]:
# جداسازی یا دسته بندی
# split

x = np.arange(8.0)


#split
print(np.split(x, 2))   # Must be divisible by the len of arrays  / باید بر تعداد مقادیر آرایه بخش پذیر باشد
## print(np.split(x, 3))  # --> error

print(np.split(x, [2, 3]))
#ary[:2]    # 0 to 2-1 = 1  -> index 0,1 
#ary[2:3]   # 2 to 3-1 = 2  -> index 2
#ary[3:]    # 3 to end      -> index 3,4,5,...

print(np.split(x, [4, 6]))
#ary[:4]    # 0 to 4-1 = 3  -> index 0,1,2,3 
#ary[4:6]   # 4 to 6-1 = 5  -> index 4,5
#ary[6:]    # 6 to end      -> index 6,7

np.split(x, [3, 5, 6, 10])
#ary[:3]    # 0 to 3-1 = 2  -> index 0,1,2 
#ary[3:5]   # 3 to 5-1 = 4  -> index 3,4
#ary[5:6]   # 5 to 6-1 = 5  -> index 5
#ary[6:10]  # 6 to 10-1 = 9 -> index 6,7, []


#hsplit
#horizontally / افقی

#2D
x = np.arange(16.0).reshape(4, 4)
a, b = np.hsplit(x, 2)

#3D
x = np.arange(8.0).reshape(2, 2, 2)
a, b= np.hsplit(x, 2)



#vsplit
# vertically  / عمودی

#2D
x = np.arange(16.0).reshape(4, 4)
a, b = np.vsplit(x, 2)
a, b, c = np.vsplit(x, np.array([3, 6]))

#3d
x = np.arange(8.0).reshape(2, 2, 2)
a, b = np.vsplit(x, 2)




# dsplit
# depth  / عمقی
x = np.arange(16.0).reshape(2, 2, 4)
a, b = np.dsplit(x, 2)
a, b, c = np.dsplit(x, np.array([3, 6]))


In [208]:
# ساخت عدد تصادفی 
# grnerate random number 

# between 0 & 1
x = np.random.random((3, 4))
print(x)

x = np.random.randint(0, 100, size=(3,4))
print(x)



[[0.50831545 0.16684751 0.77905102 0.8649333 ]
 [0.41139672 0.13997259 0.03322239 0.98257496]
 [0.37329075 0.42007537 0.05058812 0.36549611]]
[[ 9 10 27 45]
 [71 39 61 85]
 [97 44 34 34]]


In [236]:
# بدست آوردن کوچک ترین یا بزرگ ترین مقدار
# find min or max value

np.random.seed(0)

x = np.random.randint(100 , size=(3, 4))
print(x)

# minimux in all of the array / کوچک ترین آیتم در کل آرایه
print(x.min())

# minimum in the each row  / کوچک ترین در هر سطر
print(x.min(axis=1))     

#minimum in the each column / کوچک ترین در هر ستون
print(x.min(axis=0))



# index of the minimum in all / ایندکس کوچک ترین در کل آرایه
print(np.argmin(x))

# index of the minimum in each row / ایندکس کوچک ترین در هر سطر
print(np.argmin(x, axis=1))

# index of the minimum in each column / ایندکس کوچک ترین در هر ستون
print(np.argmin(x, axis=0))





[[44 47 64 67]
 [67  9 83 21]
 [36 87 70 88]]
9
[44  9 36]
[36  9 64 21]
5
[0 1 0]
[2 1 0 1]


In [254]:
# انواع ابعاد آرایه
# Types of array dimensions

a = np.array(123)
b = np.array([1,2,3])  # ((1,2,3)) or ([1,2,3])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
e = np.array( [[[[1,2,3]]]])
f = np.array([1,2,3], ndmin=10)  # [[[[[[[[[[1 2 3]]]]]]]]]]

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)
print(f.ndim)








0
1
2
3
4
10
[[[[[[[[[[1 2 3]]]]]]]]]]


5th element on 2nd dim:  10
